### ISSUE TITLE
1.0.1 release for macOS points to dkp-linux instead of dkp-osx

### ISSUE THREAD

**Issue by ihaveamac** [devkitPro/pacman#11]
In pacman.conf in the 1.0.1 package, the dkp-linux repo is accidentally used on Mac. This issue came up after a user attempted multiple installs to try and figure out why installed packages couldn’t be executed. 1.0 release doesn't have this issue.

**Comment by WinterMute** [comment]
Apologies, was fixing something minor in the packaging & neglected to check the conf.

Should be fixed now as well as adding a .plist to LaunchAgents to set env variables as per https://devkitpro.org/viewtopic.php?f=15&t=8729#p16116
