### ISSUE TITLE
devkitPPC, devkitARM and tools missing from /opt/devkitpro Mac installer

### ISSUE THREAD

**Issue by karlvoigt** [devkitPro/pacman#14]
I've tried to install Pacman on MacOS Mojave using the installer (both through simply running it and running it from terminal). However /opt/devkitpro/ remains empty except for a pacman folder which also does not contain the necessary files.

**Comment by fincs** [comment]
You only installed the package manager that is supplied in order to download products made by devkitPro. The easiest way to e.g. set up a 3DS development environment would involve this command:

```
sudo dkp-pacman -S 3ds-dev
```

For more information, please consult https://devkitpro.org/wiki/devkitPro_pacman#Using_Pacman

**Comment by karlvoigt** [comment]
Thanks! Stupid me ;)
