### ISSUE TITLE
Installation instruction for Ubuntu (Debian?) not sufficient or problem with .deb package

### ISSUE THREAD

**Issue by HorstBaerbel** [devkitPro/pacman#16]
I installed devkitpro-pacman from the 1.0.1 release .deb package as instructed on Ubuntu 18.04 and 19.04. It seems that it does not get configured correctly and throws errors on subsequent apt/dkpg installs. Also when logging in an Ubuntu system error dialog pops up. The dpkg.log told me:

> 2019-08-29 03:11:47 startup archives unpack
> 2019-08-29 03:11:47 install devkitpro-pacman:amd64 <keine> 1.0.1
> 2019-08-29 03:11:47 status half-installed devkitpro-pacman:amd64 1.0.1
> 2019-08-29 03:11:48 status unpacked devkitpro-pacman:amd64 1.0.1
> 2019-08-29 03:11:48 startup packages configure
> 2019-08-29 03:11:48 configure devkitpro-pacman:amd64 1.0.1 <keine>
> 2019-08-29 03:11:48 status unpacked devkitpro-pacman:amd64 1.0.1
> 2019-08-29 03:11:48 status half-configured devkitpro-pacman:amd64 1.0.1

So it seems not to be configured correctly. On subsequent apt/dpkg installs dpkg told me (German, but you'll figure it out):

> devkitpro-pacman (1.0.1) wird eingerichtet ...
> /var/lib/dpkg/info/devkitpro-pacman.postinst: Zeile 3: dkp-pacman-key: Befehl nicht gefunden
> /var/lib/dpkg/info/devkitpro-pacman.postinst: Zeile 4: dkp-pacman-key: Befehl nicht gefunden
> /var/lib/dpkg/info/devkitpro-pacman.postinst: Zeile 5: dkp-pacman: Befehl nicht gefunden
> dpkg: Fehler beim Bearbeiten des Paketes devkitpro-pacman (--configure):
>  »installiertes devkitpro-pacman-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 127 zurück
> libuv1:amd64 (1.24.1-1) wird eingerichtet ...
> librhash0:amd64 (1.3.8-1) wird eingerichtet ...
> cmake-data (3.13.4-1) wird eingerichtet ...
> libjsoncpp1:amd64 (1.7.4-3) wird eingerichtet ...
> cmake (3.13.4-1) wird eingerichtet ...
> Trigger für man-db (2.8.5-2) werden verarbeitet ...
> Trigger für libc-bin (2.29-0ubuntu2) werden verarbeitet ...
> Fehler traten auf beim Bearbeiten von:
>  devkitpro-pacman
> E: Sub-process /usr/bin/dpkg returned an error code (1)

I had to do:
`sudo dpkg --configure devkitpro-pacman`

Output:

> devkitpro-pacman (1.0.1) wird eingerichtet ...
> gpg: /opt/devkitpro/pacman/etc/pacman.d/gnupg/trustdb.gpg: trust-db erzeugt
> gpg: keine ultimativ vertrauenswürdigen Schlüssel gefunden
> gpg: starting migration from earlier GnuPG versions
> gpg: porting secret keys from '/opt/devkitpro/pacman/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
> gpg: migration succeeded
> gpg: Generating pacman keyring master key...
> gpg: Schlüssel 8Exxxxxxxxxx9 ist als ultimativ vertrauenswürdig gekennzeichnet
> gpg: Verzeichnis `/opt/devkitpro/pacman/etc/pacman.d/gnupg/openpgp-revocs.d' erzeugt
> gpg: Widerrufzertifikat wurde als '/opt/devkitpro/pacman/etc/pacman.d/gnupg/openpgp-revocs.d/673xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9.rev' gespeichert.
> gpg: Done
> ==> Aktualisiere Trust-Datenbank...
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: Tiefe: 0  gültig:   1  signiert:   0  Vertrauen: 0-, 0q, 0n, 0m, 0f, 1u
> ==> Füge Schlüssel aus devkitpro.gpg hinzu...
> ==> Signiere die vertrauenswürdigen Schlüssel im Schlüsselbund lokal...
>   -> Signiere Schlüssel 032Fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2 lokal...
>   -> Signiere Schlüssel BC2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1 lokal...
> ==> Importiere die Vertrauenswerte des Benutzers...
> gpg: setting ownertrust to 4
> gpg: setting ownertrust to 4
> ==> Aktualisiere Trust-Datenbank...
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: Tiefe: 0  gültig:   1  signiert:   2  Vertrauen: 0-, 0q, 0n, 0m, 0f, 1u
> gpg: Tiefe: 1  gültig:   2  signiert:   0  Vertrauen: 0-, 0q, 0n, 2m, 0f, 0u
> :: Synchronisiere Paketdatenbanken...
>  dkp-libs                 100,3 KiB  1193K/s 00:00 [######################] 100%
>  dkp-linux                 14,8 KiB  3,61M/s 00:00 [######################] 100%

After that the dpkg errors went away...

**Comment by justinkb** [comment]
on WSL with debian 10 I had to install gpg libxml2 curl via apt, fwiw

**Comment by WinterMute** [comment]
This should be fixed with 1.0.2. The instructions have also been updated to use gdebi which will pull in dependencies.

**Comment by Drakonas** [comment]
Why was the .deb file removed from the release page?
