### ISSUE TITLE
Unable to install on aarch64

### ISSUE THREAD

**Issue by martmists** [devkitPro/pacman#17]
```
$ dpkg -i devkitpro-pacman.deb
dpkg: error processing archive devkitpro-pacman.deb (--install):
 package architecture (amd64) does not match system (aarch64)
Errors were encountered while processing:
 devkitpro-pacman.deb
```

**Comment by fincs** [comment]
We don't provide binaries for AArch64, only amd64, sorry.

**Comment by martmists** [comment]
How would I go about compiling the binaries for aarch64 myself?

**Comment by WinterMute** [comment]
@martmists what hardware are you using and what OS are you running on it?

**Comment by emanrdesu** [comment]
not him but I got a similar issue but mine is arm64
my OS is chromeOS with linux beta (debian based)

**Comment by fincs** [comment]
aarch64 and arm64 are the same thing.

**Comment by WinterMute** [comment]
> not him but I got a similar issue but mine is arm64
> my OS is chromeOS with linux beta (debian based)

What's the actual hardware though? Is this a 64bit arm based Chromebook or something?

**Comment by emanrdesu** [comment]
@WinterMute yeah lscpu says the architecture is aarch64

**Comment by WinterMute** [comment]
I was actually interested in knowing the the specific hardware - i.e. pinebook or those Samsung Exynos based things or whatever.

Still. Thanks to the generosity of our donors and patrons we now have aarch64 linux hosted tools :)

See https://github.com/devkitPro/pacman/releases/latest
