### ISSUE TITLE
Ubuntu can't get "dkp-libs.db" on downloads.devkitpro.org : Connection timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by allanco12** [devkitPro/pacman#18]
I'm following the instructions for the .deb package but what I get is an error and it doesn't install the pacman package. Could someone help me? The screen output is just below:

sudo dpkg -i devkitpro-pacman.deb
[sudo] senha para *****: 
(Lendo banco de dados ... 386033 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar devkitpro-pacman.deb ...
A descompactar devkitpro-pacman (1.0.1) sobre (1.0.1) ...
Configurando devkitpro-pacman (1.0.1) ...
==> Anexando chaves de devkitpro.gpg...
==> Assinando localmente chaves confiáveis no chaveiro...
  -> Assinando localmente a chave BC26F752D25B92CE272E0F44F7FD5492264BB9D0...
  -> Assinando localmente a chave 032F4C9D0B8FF3BC84019B7862C7609ADA219C60...
==> Importando valores de ownertrust...
==> Atualizando base de dados de confiança...
gpg: não há necessidade de checagem do banco de dados de confiabilidade
:: Sincronizando a base de dados de pacotes...
erro: falha ao obter o arquivo "dkp-libs.db" de downloads.devkitpro.org : Connection timed out after 10000 milliseconds
erro: falha ao atualizar dkp-libs (erro na biblioteca de download)
erro: falha ao obter o arquivo "dkp-linux.db" de downloads.devkitpro.org : Connection timed out after 10000 milliseconds
erro: falha ao atualizar dkp-linux (erro na biblioteca de download)
erro: failed to synchronize all databases
dpkg: erro ao processar o pacote devkitpro-pacman (--install):
 installed devkitpro-pacman package post-installation script subprocess returned error exit status 1
Erros foram encontrados durante o processamento de:
 devkitpro-pacman

**Comment by Diegoisawesome** [comment]
I'm having the same issue. I was able to temporarily fix it by adding `options single-request` to /etc/resolv.conf but now it's not working.

**Comment by WinterMute** [comment]
What's the output of `dig downloads.devkitpro.org`?

**Comment by Diegoisawesome** [comment]
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> downloads.devkitpro.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36720
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;downloads.devkitpro.org.       IN      A

;; ANSWER SECTION:
downloads.devkitpro.org. 300    IN      A       104.28.14.12
downloads.devkitpro.org. 300    IN      A       104.28.15.12

;; Query time: 58 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Thu Feb 27 18:26:01 EST 2020
;; MSG SIZE  rcvd: 84
```

**Comment by Diegoisawesome** [comment]
Any updates? Things still aren't working for me.

**Comment by WinterMute** [comment]
> Any updates? Things still aren't working for me.

No, sorry. Have you tried using different DNS servers? What are you running at 192.168.1.254?

**Comment by Diegoisawesome** [comment]
That was actually forwarded to me from someone I was troubleshooting this with, and I would assume that's just their router. Mine has my router as the server:

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> downloads.devkitpro.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3939
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;downloads.devkitpro.org.       IN      A

;; ANSWER SECTION:
downloads.devkitpro.org. 300    IN      A       104.28.15.12
downloads.devkitpro.org. 300    IN      A       104.28.14.12

;; AUTHORITY SECTION:
devkitpro.org.          86400   IN      NS      lara.ns.cloudflare.com.
devkitpro.org.          86400   IN      NS      jack.ns.cloudflare.com.

;; ADDITIONAL SECTION:
lara.ns.cloudflare.com. 170726  IN      A       173.245.58.128
lara.ns.cloudflare.com. 170726  IN      AAAA    2606:4700:50::adf5:3a80
jack.ns.cloudflare.com. 170691  IN      A       173.245.59.121
jack.ns.cloudflare.com. 24416   IN      AAAA    2606:4700:58::adf5:3b79

;; Query time: 12 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Apr 02 18:09:15 PDT 2020
;; MSG SIZE  rcvd: 227
```

I think the issue has to do with IPv6 because after restarting my Pihole (as I saw in the dig output that it wasn't being used as my DNS), things work, and this is the output of dig:

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> downloads.devkitpro.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19791
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;downloads.devkitpro.org.       IN      A

;; ANSWER SECTION:
downloads.devkitpro.org. 171    IN      A       104.28.15.12
downloads.devkitpro.org. 171    IN      A       104.28.14.12

;; Query time: 7 msec
;; SERVER: 192.168.1.2#53(192.168.1.2)
;; WHEN: Thu Apr 02 18:15:49 PDT 2020
;; MSG SIZE  rcvd: 84
```

**Comment by Sierraffinity** [comment]
Still getting this same issue...
`; <<>> DiG 9.16.1-Ubuntu <<>> downloads.devkitpro.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53117
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;downloads.devkitpro.org.       IN      A

;; ANSWER SECTION:
downloads.devkitpro.org. 280    IN      A       104.28.15.12
downloads.devkitpro.org. 280    IN      A       104.28.14.12

;; Query time: 13 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Mon Apr 27 11:44:03 PDT 2020
;; MSG SIZE  rcvd: 84`

**Comment by WinterMute** [comment]
What do you get when you visit https://downloads.devkitpro.org in a web browser?

**Comment by Sierraffinity** [comment]
"Hello world" but I think I've figured it out.
I have my network set up with "two" DNS servers, my router's and my Pihole. My router assigns the Pihole's IP as the DNS server in DHCP (192.168.1.2) but also serves its own as the alternate (192.168.1.1). Seems like my Pihole dies occasionally, and most things on my network are able to gracefully fall back on the alternate server, but not pacman.

If my Pi is down and it's the first entry in /etc/resolv.conf, it will be unable to resolve. If I swap the order of the DNS servers in the file and put my router's DNS as the first choice, things start to work again. You can easily replicate my test conditions by adding a garbage IP that you know isn't serving DNS to the top of /etc/resolv.conf.

**Comment by WinterMute** [comment]
Testing latest 1.0.2 on debian under the conditions described (bogus nameserver at top of resolv.conf) results in delays but appears to fall back fine.
