### ISSUE TITLE
Support of Win32

### ISSUE THREAD

**Issue by FrankHB** [devkitPro/pacman#2]
Can the toolchains hosted in Win32 provided as packages? (Having a fresh msys2 environment seems not very wise when there is already a msys2 instance installed in the system.)

Please update the release note to clarify the status of support.

**Comment by WinterMute** [comment]
https://github.com/devkitPro/pacman/releases/latest

"For users already using a distro which provides pacman please follow these instructions. This also applies to Fedora where you can install pacman using sudo dnf install pacman and users who wish to use an existing msys2 install. If you're using a pre-existing msys2 install then please also set environment variables as follows :-"

**Comment by FrankHB** [comment]
Got it. Thank you!
