### ISSUE TITLE
Typos in package description

### ISSUE THREAD

**Issue by Crayon2000** [devkitPro/pacman#21]
There are some typos in the package description when running `gdebi devkitpro-pacman.amd64.deb`
The text says:
```text
devkitPro package manager
  A lightly customised build of arch pacman used to manage the tools and libraries maintained and distrributed by devktPro.
```
* dist**r**ributed  = distributed
* devktPro = devk**i**tPro

**Comment by WinterMute** [comment]
Really don't like typos, do you? :P

Fixed this earlier. These aren't really officially released as yet
