### ISSUE TITLE
Mirrors on Windows x64 MSYS2 not working.

### ISSUE THREAD

**Issue by foxsouns** [devkitPro/pacman#25]
I'm not sure where to leave this, and I'm probably at fault here somehow, but dkp-pacman does not seem able to fetch anything from the dkp mirrors. It all _looks_ fine, until you try to sync something, then it spits out this. I used the installer, and saw the inconsistency between `https://downloads.devkitpro.org/` and `https://pkg.devkitpro.org/`, and tried both, but to no avail. Same end result.
https://gist.github.com/foxsouns/14ba753ce7c8ae693e1725f2b16489f3

**Comment by WinterMute** [comment]
What IP address are you accessing the server from?

**Comment by foxsouns** [comment]
@WinterMute I'm not crazy about putting my IP out here in a public GH Issue, but if you could send me an email to me at renastics@protonmail.ch, I would gladly reply.

**Comment by sayabiws** [comment]
Unsure whether this is the right place but I'm having a similar error when updating my packets on Arch. I've added the repository to my own Pacman which to my knowledge is fine.

Whenever I try to update my packets I get a 404 error when synchronizing package databases:
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 [...]
 dkp-libs is up to date
error: failed retrieving file 'dkp-linux.db' from pkg.devkitpro.org : The requested URL returned error: 404
error: failed to update dkp-linux (failed to retrieve some files)
 [...]
error: failed to synchronize all databases
error installing repo packages
```
*(note: I've removed irrelevant mirror lists for clarity)*

I've tried with both `https://downloads.devkitpro.org/` and `https://pkg.devkitpro.org`, and the issue persists.

**Comment by foxsouns** [comment]
@sayabiws I noticed you get a 404 (Not found), and I get a 403 (Forbidden). Does opening either of the package links provide a simple message? For me, opening either of them in a browser produces "Hello world".

**Comment by sayabiws** [comment]
Ah, my bad. Though, both produce a "Hello world" from a browser as well for me, so I'm unsure what the problem is here.

I'm really sorry for hijacking your issue like this, btw :smile:

**Comment by foxsouns** [comment]
@sayabiws Oh, don't worry! I'm sure that WinterMute knows how to fix this; for both of the error codes; but let me regurgitate what I've seen on the internet: are you using a proxy of any sort in your terminal? Did you get the right keyserver? Did you spell it right?

**Comment by foxsouns** [comment]
IIRC the keyserver that worked for me on arch was buried in a forum somewhere.

**Comment by sayabiws** [comment]
I found the problem: the URL for `dkp-linux` changed from `https://[pkg|downloads].devkitpro.org/packages/linux` to `https://[pkg|downloads].devkitpro.org/packages/linux/$arch/` (found [here](https://devkitpro.org/wiki/devkitPro_pacman)). Editing `/etc/pacman.conf` with the correct URL fixed my issue. Thanks a lot!

**Comment by foxsouns** [comment]
Nice! I'm guessing, since my IP belongs to a larger organization, that it got blacklisted for some random reason or something. Guess I'm gonna have to wait: gonna see if I can't reproduce this on a quick xubuntu live drive.

**Comment by foxsouns** [comment]
Yup: my organization was blocking anything under `http://`; after I changed the links in to `https://` it worked fine! Closing this now; thanks for the help!
