### ISSUE TITLE
Switch-Tools is Corrupted (Invalid Checksum)

### ISSUE THREAD

**Issue by ianmarmour** [devkitPro/pacman#26]
I know this isn't the correct repo for this issue however when attempting to do a clean install of switch-tools on Ubuntu you get the following error,

```
:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 switch-tools-1.10.0-3-x86_64                                                                                 82.1 KiB  2.67M/s 00:00 [##################################################################################] 100%
(1/1) checking package integrity                                                                                                      [##################################################################################] 100%
:: File /opt/devkitpro/pacman/var/cache/pacman/pkg/switch-tools-1.10.0-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] Y
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.
```

also see

```
error: switch-tools: signature from "Dave Murphy (WinterMute) <davem@devkitpro.org>" is invalid
:: File /var/cache/pacman/pkg/switch-tools-1.10.0-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
```

That particular repo is a fork of the switchbrew repo and doesn't have issues enabled so this has probably flown under the radar for a while.

**Comment by ianmarmour** [comment]
I can verify that all installation instructions regarding installing the keyring, updating etc were performed per the wiki's guidance and that this is impacting multiple users.

**Comment by WinterMute** [comment]
> I know this isn't the correct repo for this issue

So don't open issues on unrelated repos?

> That particular repo is a fork of the switchbrew repo and doesn't have issues enabled so this has probably flown under the radar for a while.

I have no idea what you're talking about.
