### ISSUE TITLE
python2.7 is needed as a dependency for gdb

### ISSUE THREAD

**Issue by jeremyherbert** [devkitPro/pacman#27]
Hi,

I just tried to install this on Xubuntu 20.04 and was unable to run gdb because of this error:

```
./arm-none-eabi-gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

The solution is to install the package `libpython2.7` with apt. It would be helpful if this was a dependency in the install chain for devkitpro.

**Comment by WinterMute** [comment]
We've removed python dependencies for the gdb binaries pending some sensible way to support it if feasible.
