### ISSUE TITLE
Installing packages

### ISSUE THREAD

**Issue by JakeGoldmanCode** [devkitPro/pacman#28]
(Debian Linux)

When installing packages using "dkp-pacman -Sl" from the wiki, I get the error "error: repository "3ds-dev" was not found."

How do I fix this

**Comment by JakeGoldmanCode** [comment]
wait i fixed it

**Comment by 8-BIT-DEV** [comment]
are you going to tell us how you fixed it?

**Comment by WinterMute** [comment]
> are you going to tell us how you fixed it?

Presumably the OP realised -Sl lists packages and that installing packages and groups is done with -S

**Comment by JakeGoldmanCode** [comment]
> > are you going to tell us how you fixed it?
> 
> Presumably the OP realised -Sl lists packages and that installing packages and groups is done with -S

ye[
