### ISSUE TITLE
error: error while reading package on MacOS

### ISSUE THREAD

**Issue by EimaMei** [devkitPro/pacman#30]
When I was trying to install 3DS development on my iMac, it always gave me this specific error when I entered `sudo dkp-pacman -S 3ds-dev`:
```
:: Proceed with installation? [Y/n] 
(1/1) checking package integrity                                                                  [##########################################################] 100%
(1/1) loading package files                                                                       [##########################################################] 100%
error: error while reading package /opt/devkitpro/pacman/var/cache/pacman/pkg/3ds-examples-20210610-1-any.pkg.tar.xz: Pathname can't be converted from UTF-8 to current locale.
error: failed to commit transaction (libarchive error)
Errors occurred, no packages were upgraded.
```
I didn't understand why this was happening, since I was able to download the wii development on the same computer and it had no trouble. Then I tried installing each 3DS member on its own, and I realized that the error was coming from `2) 3ds-examples` every time because it always gave me that specific error mentioned above, while the others installed fine with no problem. Even though I know what's causing the error, I still don't know how to fix it.

**Comment by fincs** [comment]
What's your locale's text encoding? Fwiw, the 3ds-examples package contains a folder with Japanese characters in order to show that RomFS supports arbitrary Unicode codepoints and is not restricted to 0-127. For reference, UTF-8 is normally the text encoding used in modern Unix like operating systems such as macOS.

**Comment by EimaMei** [comment]
Sorry but I don't know how I can check my locale's text encoding (if I did, I would have probably known why I got that error, which I didn't). How can I check it?

**Comment by WinterMute** [comment]
I managed to reproduce this on my macbook & I've updated the package. Still investigating what exactly is causing the issue but hopefully the latest version works for you. You can update with `sudo dkp-pacman -Syu` Let us know if that works or you still have problems.

**Comment by EimaMei** [comment]
Using `sudo dkp-pacman -Syu` and then `sudo dkp-pacman -S 3ds-dev`, it worked and I was able to download the 3ds packges! I was even able to only download the 3ds-example package without getting that error.

**Comment by WinterMute** [comment]
Was prompted to look at this again recently after encountering a similar issue & I'm not pretty sure we've solved this permanently.
