### ISSUE TITLE
killed: 9 error on macos

### ISSUE THREAD

**Issue by aem111607** [devkitPro/pacman#32]
when i try to run dkp-pacman i get the error "Killed: 9"
macos 12.2, M1 mba

**Comment by WinterMute** [comment]
Try the installer here https://github.com/devkitPro/pacman/releases/tag/v6.0.2

**Comment by WinterMute** [comment]
Presuming fixed after testing on M1 machines.

**Comment by aem111607** [comment]
Yes, it's fixed now.
