### ISSUE TITLE
.deb not comptabible with Ubuntu 16.04

### ISSUE THREAD

**Issue by freshollie** [devkitPro/pacman#33]
Hey,

I understand Ubuntu 16.04 is old, however would be cool if it was supported:

Firstly, the `gpg` requirement in the `.deb` is not compatible (should be `gnupg`)
```
 devkitpro-pacman depends on gpg; however:
  Package gpg is not installed.
```

If we force that (assuming gpg is available on the system):

Seems there is a requirement for a version of glibc higher than available on ubuntu 16.04

```
pacman-conf: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by pacman-conf)
pacman-conf: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by pacman-conf)
pacman-conf: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by pacman-conf)
```

```
$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by WinterMute** [comment]
Ubuntu 16.04 reached end of life on April 2021. This means that no further
security updates are available. You should update to 20.04 as soon as
practical.

**Comment by freshollie** [comment]
FYI, upgraded to Ubuntu 22, and now `devkitpro-pacman : Depends: libssl1.1 but it is not installable`.

Had to manually add the Ubuntu 21 repos.
```
echo "deb http://security.ubuntu.com/ubuntu impish-security main" | sudo tee /etc/apt/sources.list.d/impish-security.list

sudo apt-get update
```

Apparently Ubuntu 22 uses libssl3
