### ISSUE TITLE
Installation error - "Depends: libssl1.1 but it is not installable" on Ubuntu 22.04 (Win11, WSL2)

### ISSUE THREAD

**Issue by sirocyl** [devkitPro/pacman#34]
**Outdated installation method used. Instructions from https://devkitpro.org/wiki/devkitPro_pacman#Installing_devkitPro_Pacman should have been followed**

**Version:** devkitPro pacman release, version 1.0.2, dated 6/30/2020; current as of 5/28/2022. Retrieved from releases [here]().

# Issue:
The following error is produced when attempting to install devkitpro-pacman:
> `Depends: libssl1.1 but it is not installable`

The installation aborts soon after.

# Log:

```
ttrue@Hyperion:~$ sudo apt install ./devkitpro-pacman.amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'devkitpro-pacman' instead of './devkitpro-pacman.amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 devkitpro-pacman : Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

# Environment:
- Windows 11 22H2 RTM x64
- Ubuntu 22.04 LTS, installed from Microsoft Store
- WSL 2 (VM-based)
- Latest Windows and Ubuntu updates are installed.

# Impact:
This affects Ubuntu 22.04.

This was tested to fail on WSL 2 on Windows 11 x64; but is also expected to fail on WSL 1, WSL 2 and 1 on Windows 10, and any VM, containerized or native-installed Ubuntu 22.04 environments, both amd64 and arm64.
The workaround listed above, which works on WSL 2, is expected to work on all the other supported environments for Ubuntu 22.04 where devkitpro-pacman can install and run.

**Comment by WinterMute** [comment]
You're using old installation instructions and old deb packages. I've updated the instructions on the releases here & removed the outdated packages.

Recommend you remove the broken package using ```sudo dpkg --remove --purge devkitpro-pacman``` then follow instructions from https://devkitpro.org/wiki/devkitPro_pacman#Installing_devkitPro_Pacman

**Comment by sirocyl** [comment]
Acknowledged; I see the changes made now, and the .deb having been removed from the releases page.

This method does work, and solves the issue. `sudo dpkg --purge` implies `--remove`, though, so I used `sudo dpkg --purge devkitpro-pacman libssl1.1` instead.

I'll remove the workaround and make necessary retractions to advice for the outdated method. Thank you!
