### ISSUE TITLE
Does not install on M2 MacBooks

### ISSUE THREAD

**Issue by 315332** [devkitPro/pacman#35]
[~/Downloads]$ sudo installer -pkg devkitpro-pacman-installer.pkg -verbose -target /
installer: Package name is
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing ….....
installer: Waiting for other installations to complete….....
installer: Configuring the installation….....
installer:
#
installer: Writing files….....
#
installer: Moving items into place….....
#
installer: Running package scripts….....
#
installer: Running package scripts….....
#
installer: Running package scripts….....
#
installer: Running package scripts….....
#
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Validating packages….....
#
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “devkitpro-pacman-installer.pkg”.)

**Comment by WinterMute** [comment]
The installer at https://github.com/devkitPro/pacman/releases/tag/v6.0.2 should hopefully work
