### ISSUE TITLE
error while installing devkitpro Pac-Man

### ISSUE THREAD

**Issue by TheGhostboi64** [devkitPro/pacman#36]
When I did the following command `sudo pacman -U devkitpro-keyring.pkg.tar.xz `,
I get `error: dkp-libs: signature from "fincs <fincs@devkitpro.org>" is unknown trust
error: database 'dkp-libs' is not valid (invalid or corrupted database (PGP signature))
loading packages...
warning: devkitpro-keyring-20180316-1 is up to date -- reinstalling
error: failed to prepare transaction (invalid or corrupted database) `. Is there anyway I can fix?

**Comment by oreo639** [comment]
You are supposed to install `devkitpro-keyring` before you add the dkp-libs/dkp-linux repos.

iirc you should be able to do `sudo rm -r /var/lib/pacman/sync` then follow the instructions here in order:
https://devkitpro.org/wiki/devkitPro_pacman

**Comment by TheGhostboi64** [comment]
I did install the devkitpro keyring. I'm trying to do the customizing Pac-Man section if you're wondering.

**Comment by TheGhostboi64** [comment]
I'll just try to uninstall and reinstall pacman

**Comment by TheGhostboi64** [comment]
ok I think I fixed it, but if I comment the dkplibs server, I get this. `call to execv failed (No such file or directory)
error: command failed to execute correctly`
