### ISSUE TITLE
Build for armel

### ISSUE THREAD

**Issue by PokeyManatee4** [devkitPro/pacman#37]
Im trying to compile a wii u app on armel but i cant get pacman because it dont support armel

**Comment by WinterMute** [comment]
What device are you trying to compile on?

**Comment by PokeyManatee4** [comment]
Android with root and termux

**Comment by WinterMute** [comment]
Main reason for asking is that debian has dropped armel support & moved to armhf so providing armel binaries isn't straightforward.  Depending on the device there may be other options.

**Comment by PokeyManatee4** [comment]
@WinterMute what about armhf?

**Comment by WinterMute** [comment]
> @WinterMute what about armhf?

What's the device?

**Comment by PokeyManatee4** [comment]
Linux

**Comment by WinterMute** [comment]
> Linux


Um, no. Linux is an OS. What piece of hardware are you trying to compile things on? A phone, a tablet? Raspberry Pi? What specific model is it?

**Comment by PokeyManatee4** [comment]
MT8167A

**Comment by WinterMute** [comment]
MT8167A is aarch64, have you installed a 32bit OS on it? Did it come with one?

**Comment by PokeyManatee4** [comment]
my reads armeabi-v7a

**Comment by WinterMute** [comment]
> my reads armeabi-v7a

OK but what's the actual device? Make & model if you have it. Did it come with a 32bit OS on there? Did you install a 32bit linux on it?

**Comment by PokeyManatee4** [comment]
17/07 &100005206 & No, I did not.
