### ISSUE TITLE
Change in distribution method

### ISSUE THREAD

**Issue by turtleisaac** [devkitPro/pacman#38]
Hey, quick question about a change in distribution method that seems to have happened.

I’m pretty sure you guys had .deb files previously available in the releases for installing on Debian Linux, but those seem to have disappeared now? I’ve seen you have an alternative way to install dkp-pacman with a shell script now, but I’m wondering what exactly happened that made you decide to change what was a perfectly functional distribution method.

Sorry if this seems a bit rude, I’m just wondering what went on behind the scenes to influence that decision

**Comment by fincs** [comment]
devkitPro pacman is no longer distributed as a loose .deb file; it is now distributed through a proper APT repository, which allows for things such as dependencies to be correctly resolved, as well as the correct package (x86_64 or aarch64) to be automatically downloaded. If you read the shell script, you'll see that it automatically configures said repository on your machine, together with the required GPG signing key needed to verify signatures.
