### ISSUE TITLE
Can't install dkp-pacman due to insufficient permissions to read the pacman keyring

### ISSUE THREAD

**Issue by Axcellerator** [devkitPro/pacman#41]
![pacman](https://user-images.githubusercontent.com/77007734/214860289-a9a60a15-bf20-4993-8adf-427a81bcd537.png)

**Comment by LOuroboros** [comment]
Context: I'm chit-chatting with Axcellerator.

While I personally never came across this error myself, I did see others getting roadblocked by it in the past too too.

Currently,  Axcellerator is using Ubuntu 18.04.6 LTS.
I just noticed that for the process we're performing, which is to build the Pokémon Decompilation Projects, [someone else came across this exact same issue and they solved it by updating their installation of Ubuntu](https://www.pokecommunity.com/showpost.php?p=10541422&postcount=97), so I need to ask; is there a chance that devkitPro simply doesn't support that version of Ubuntu anymore, [despite the fact it receives official support until April 2028](https://ubuntu.com/about/release-cycle)?

**Comment by AndrewPiroli** [comment]
Ubuntu 18.04 ships with glibc 2.27 and the binary distribution of pacman is compiled against glibc 2.28. This should have been caught at install time but the dekvitpro-pacman package does not properly declare the required versions of its dependencies.

You have a few options here:

- Upgrade your system, Ubuntu 18.04 will be EoL in 3 months.
- Find a binary distribution of pacman that supports your old libc and manually add the dkp repos
- Compile pacman yourself and manually add the dkp repos
- Go through the rigamarole of building a newer glibc, installing it to a non-standard prefix and convincing the dynamic loader to use it when launching pacman.

**Comment by fincs** [comment]
You seem to be using Ubuntu 18.04, which is two LTS releases behind, and which enters end of life on April 30, 2023 (3 months from now). I'd suggest you upgrade your system to the current Ubuntu LTS release (22.04).

The baseline version of Ubuntu that is compatible with software packages distributed by devkitPro is currently Ubuntu 20.04. There may be unannounced changes to the baseline in the future.

**Comment by LOuroboros** [comment]
My comment was most definitely not off-topic. It provided context. Marking it as off-topic was rather rude.

Thanks for addressing the issue though. Axcellerator already updated to Ubuntu 22 and I'll adjust the tutorial later today too suggesting the people to install the latest LTS version of Ubuntu.
