### ISSUE TITLE
What Is with the XDG_DATA_HOME and XDG_DATA_DIRS Environment Variables?

### ISSUE THREAD

**Issue by P0W3** [devkitPro/pacman#42]
They are already in the "/opt/devkitpro" directory.

I have the "C:\devkitPro" directory.

[00XX00XX.txt](https://github.com/devkitPro/pacman/files/10800770/00XX00XX.txt)

**Comment by WinterMute** [comment]
This is not windows pacman and we neither supply nor support the packages you're trying to install.
