### ISSUE TITLE
macOS package empty?

### ISSUE THREAD

**Issue by Flygsand** [devkitPro/pacman#49]
The macOS pkg file in Releases is only 1.25 KB and doesn't seem to install anything.

**Comment by WinterMute** [comment]
If you followed instructions it should have installed devkitPro pacman which is a package manager. To obtain the tools & libraries you need to install the appropriate packages, see https://devkitpro.org/wiki/Getting_Started#Unix-like_platforms

**Comment by Flygsand** [comment]
It does not appear to install pacman:

```
mh@mac ~ % dkp-pacman
zsh: command not found: dkp-pacman
mh@mac ~ % sudo find / -name dkp-pacman 2>/dev/null
mh@mac ~ %
```

But now I think I know why. I expected the package to contain files, but the installer appears to be a script that downloads another installer for the correct architecture and installs that. The issue in my case is that `pkg.devkitpro.org` blocks my VPN's IP (403). The installer script doesn't catch that.

```
mh@mac ~ % cat /tmp/devkitpro-pacman-installer.x86_64.pkg 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.56 (Debian) Server at pkg.devkitpro.org Port 443</address>
</body></html>
```

**Suggestion:** In the `preinstall` script, consider setting `set -eo pipefail` to fail fast as well as adding the `-f` flag to curl to make it fail on non-successful HTTP status codes.

I will close this issue. Thanks for your quick response.

**Comment by kwccoin** [comment]
Use my native home ip still no good.  Have you resolved the issue using home ip.

**Comment by Flygsand** [comment]
@kwccoin Yes, it worked for me with my home IP.
