### ISSUE TITLE
Question about a seemingly inexplicable ban from devkitpro's servers

### ISSUE THREAD

**Issue by korbosoft** [devkitPro/pacman#51]
Before you close this issue, please keep in mind i can't really ask this anywhere else.

I was trying to set up devkitpro on my computer, and when i ran Paru, a package manager, I found out i was suddenly banned from there. From what i have seen, I may have done something deemed too suspicious by the servers.

**Comment by korbosoft** [comment]
Probably isn't enough proof to show i'm not one of the bad guys, but I do have a Wii homebrew app on here.

**Comment by korbosoft** [comment]
I think i know the problem now, I set pacman to download up to 8 packages at the same time, which may have been seen as unwanted behavior.

**Comment by WinterMute** [comment]
> I think i know the problem now, I set pacman to download up to 8 packages at the same time, which may have been seen as unwanted behavior.

That shouldn't cause any issues. Can you let me know what IP you're accessing from?

**Comment by korbosoft** [comment]
Sure! where can i contact you?

**Comment by WinterMute** [comment]
> Sure! where can i contact you?

support@devkitpro.org will reach me.

**Comment by korbosoft** [comment]
I have sent an email.

**Comment by WinterMute** [comment]
Just a minor hiccup with a fail2ban filter. It's nothing to worry about, the ban was automatically lifted earlier & I've tweaked some settings so it hopefully shouldn't happen again.
