### ISSUE TITLE
Unsupported protocol error with libcurl.a

### ISSUE THREAD

**Issue by drewsucksatlife** [devkitPro/pacman#8]
Whenever I use switch-curl, I'm unable to use an https site because I get an unsupported protocol error with it.

**Comment by WinterMute** [comment]
correct. switch libcurl does not yet have https support.

It's being worked on, no ETA is available.

**Comment by WinterMute** [comment]
and actually this is the pacman repo for osx/linux

**Comment by drewsucksatlife** [comment]
@WinterMute, the libcurl package is on here, nowhere else to report it

**Comment by fincs** [comment]
It's not here. It's over at https://github.com/devkitPro/pacman-packages
