### ISSUE TITLE
Package installer fails on OSX High Sierra

### ISSUE THREAD

**Issue by Pomettini** [devkitPro/pacman#9]
I've tried to install pacman with the .pkg installer on my Macbook Pro with OSX 10.13.6 High Sierra but it gets an error during the install. I couldn't get the error because it doesn't save the logs anywhere. I tried both with 1.01 and 1.00. Any clue? Thank you.

**Comment by WinterMute** [comment]
Can you try it from a terminal and see if it's any more informative?

> sudo installer -verbose -pkg  devkitpro-pacman-installer.pkg -target /

**Comment by Pomettini** [comment]
I tried running that command from the terminal. I got no errors and the installation went fine. But now when I try to run the pacman command it says that cannot be found. I checked in /usr/local/bin but it's not there. Any guess?

**Comment by SegFault42** [comment]
pacman is installed in /opt/devkitpro/pacman/bin

you can add the path in $PATH

**Comment by Pomettini** [comment]
Thank you @SegFault42, got it working! 👍

**Comment by Pomettini** [comment]
2to3                     gdir                     lua-5.3
2to3-2                   gdircolors               lua5.3
2to3-2.7                 gdirname                 luac
RemoteUpdateManager      gdk-pixbuf-csource       luac-5.3
adb                      gdk-pixbuf-pixdata       luac5.3
apm                      gdk-pixbuf-query-loaders luarocks
arm-none-eabi-addr2line  gdk-pixbuf-thumbnailer   luarocks-5.3
arm-none-eabi-ar         gdu                      luarocks-admin
arm-none-eabi-as         gecho                    luarocks-admin-5.3
arm-none-eabi-c++        genv                     lzcat
arm-none-eabi-c++filt    gexpand                  lzcmp
arm-none-eabi-cpp        gexpr                    lzdiff
arm-none-eabi-elfedit    gfactor                  lzegrep
arm-none-eabi-g++        gfalse                   lzfgrep
arm-none-eabi-gcc        gfmt                     lzgrep
arm-none-eabi-gcc-5.4.1  gfold                    lzless
arm-none-eabi-gcc-ar     ggroups                  lzma
arm-none-eabi-gcc-nm     ghead                    lzmadec
arm-none-eabi-gcc-ranlib ghostid                  lzmainfo
arm-none-eabi-gcov       gid                      lzmore
arm-none-eabi-gcov-tool  ginstall                 markdown_py
arm-none-eabi-gdb        gio                      md5sum
arm-none-eabi-gdb-py     gio-querymodules         mergecap
arm-none-eabi-gprof      gjoin                    mix
arm-none-eabi-ld         gkill                    mpg123
arm-none-eabi-ld.bfd     glib-compile-resources   mpg123-id3dump
arm-none-eabi-nm         glib-compile-schemas     mpg123-strip
arm-none-eabi-objcopy    glib-genmarshal          out123
arm-none-eabi-objdump    glib-gettextize          pal2rgb
arm-none-eabi-ranlib     glib-mkenums             pango-view
arm-none-eabi-readelf    glink                    partutil
arm-none-eabi-size       gln                      pbr
arm-none-eabi-strings    glogname                 pcre-config
arm-none-eabi-strip      gls                      pcregrep
as-gbz80                 gmd5sum                  pcretest
as-z80                   gmkdir                   pip
atom                     gmkfifo                  pip2
bazel                    gmknod                   pip2.7
bazel-real               gmktemp                  pip3
bdmesg                   gmv                      pip3.6
boot1-install            gnice                    pkg-config
brew                     gnl                      png-fix-itxt
cairo-sphinx             gnohup                   pngfix
cairo-trace              gnproc                   ppm2tiff
capinfos                 gnumfmt                  prl_convert
cargo                    gobject-query            prl_disk_tool
cargo-fmt                god                      prl_perf_ctl
cargo.old                gpaste                   prlcore2dmp
ccache-swig              gpathchk                 prlctl
ccmake                   gpinky                   prlexec
chardetect               gpr                      prlsrvctl
cjpeg                    gprintenv                pycodestyle
clover-genconfig         gprintf                  pydoc
cmake                    gptx                     pydoc2
cmakexbuild              gpwd                     pydoc2.7
coremlconverter          gr2fonttest              pyflakes
cpack                    greadlink                pylint
ct_run                   grealpath                pyreverse
ctest                    gresource                python
dftest                   grm                      python-config
dialyzer                 grmdir                   python2
djpeg                    gruncon                  python2-config
dkp-makepkg              gseq                     python2.7
dkp-pacman               gsettings                python2.7-config
dkp-pacman-key           gsha1sum                 pythonw
dkp-repo-add             gsha224sum               pythonw2
dkp-repo-remove          gsha256sum               pythonw2.7
dmtracedump              gsha384sum               randpkt
dumpcap                  gsha512sum               raw2tiff
easy_install             gshred                   rawshark
easy_install-2.7         gshuf                    rdjpgcom
easy_install-3.6         gsleep                   realpath
editcap                  gsort                    redis-benchmark
elixir                   gsplit                   redis-check-aof
elixirc                  gstat                    redis-check-rdb
epmd                     gstdbuf                  redis-cli
epylint                  gstty                    redis-sentinel
erl                      gsum                     redis-server
erlc                     gsync                    rls
escript                  gtac                     run_erl
etc1tool                 gtail                    saved_model_cli
exercism                 gtee                     sdcc
f2py                     gtest                    sdcpp
f2py2.7                  gtester                  sdl-config
f2py3.6                  gtester-report           sdl2-config
fastboot                 gtimeout                 smtpd.py
fax2ps                   gtk-builder-tool         smtpd2.7.py
fax2tiff                 gtk-encode-symbolic-svg  smtpd2.py
fc-cache                 gtk-launch               sqlite3
fc-cat                   gtk-query-immodules-3.0  stack
fc-conflist              gtk-query-settings       swig
fc-list                  gtk3-demo                symilar
fc-match                 gtk3-demo-application    tensorboard
fc-pattern               gtk3-icon-browser        text2pcap
fc-query                 gtk3-update-icon-cache   tiff2bw
fc-scan                  gtk3-widget-factory      tiff2pdf
fc-validate              gtouch                   tiff2ps
fdisk440                 gtr                      tiff2rgba
flake8                   gtrue                    tiffcmp
freetype-config          gtruncate                tiffcp
fribidi                  gtsort                   tiffcrop
g-ir-annotation-tool     gtty                     tiffdither
g-ir-compiler            guname                   tiffdump
g-ir-generate            gunexpand                tiffinfo
g-ir-inspect             guniq                    tiffmedian
g-ir-scanner             gunlink                  tiffset
g[                       guptime                  tiffsplit
gapplication             gusers                   to_erl
gb2sum                   gvdir                    tshark
gbase32                  gwc                      unlzma
gbase64                  gwho                     unxz
gbasename                gwhoami                  virtualenv
gcat                     gyes                     wget
gchcon                   hb-ot-shape-closure      wheel
gchgrp                   hb-shape                 wheel3
gchmod                   hb-subset                wireshark
gchown                   hb-view                  wrjpgcom
gchroot                  hprof-conv               wx-config
gcksum                   idle                     wxrc
gcomm                    idle2                    wxrc-3.0
gcp                      idle2.7                  xz
gcsplit                  idn2                     xzcat
gcut                     iex                      xzcmp
gdate                    isort                    xzdec
gdbm_dump                jpegtran                 xzdiff
gdbm_load                lcc                      xzegrep
gdbmtool                 libpng-config            xzfgrep
gdbus                    libpng16-config          xzgrep
gdbus-codegen            link-gbz80               xzless
gdd                      link-z80                 xzmore
gdf                      lua

**Comment by WinterMute** [comment]
Everything installed fine, the dkp- binaries are there.

https://devkitpro.org/wiki/devkitPro_pacman#Using_Pacman

> The customised pacman we ship for OSX and debian based distros is entirely self-contained within /opt/devkitpro/pacman. To avoid polluting the system and avoid clashes with system tools or games which may share the same name as pacman binaries we install helper scripts in /usr/local/bin which temporarily set path and forward to the custom binaries. This means you substitute dkp-pacman for pacman on those systems.
